species: arabidopsis

seq_info:
  type: WGS
  mode: PE

path: /home/xfu/Git/TSDfinder/fastq

samples:
  - Se-0

cpu: 30

Rscript_path: /home/xfu/R/3.2.4/bin/Rscript

adapter: /home/xfu/miniconda2/envs/gmatic/share/trimmomatic/adapters/TruSeq3-PE-2.fa

index: /home/xfu/Gmatic5/genome/tair10/tair10

IGV: /home/xfu/igv/genomes/tair10.genome

TE_coord: TE/TE_coordinates.bed

max_len: 100

min_split_reads: 3

maxcov: 60
